### ISSUE TITLE
Unable to configure it properly.

### ISSUE THREAD

**Issue by pratapsingh** [helli0n/kafka-monitoring#1]
Do we need to install "zabbix-java-gataway" on zabbix-server or kafka host?

Which IP we should give here? "JavaGateway=IP_address_java_gateway" Zabbix server IP or kafka host IP, If it is kafka server IP then how can we configure multiple kafka hosts.

I am getting below error after configuring as per the doc and my understanding 

`java.net.SocketTimeoutException: connection timed out: service:jmx:rmi:///jndi/rmi://[Kafka-Host-IP]:12345/jmxrm  
`

_**Kafka-Host-IP is provided as "JavaGateway" IP in zabbix_server.conf ._

Port are allowed no issue with firewall and connectivity.

**Comment by helli0n** [comment]
@pratapsingh
You have to install java-getaway on zabbix-server. When java-getaway will monitoring a lot of java consoles.
