### ISSUE TITLE
JMXDiscovery-0.0.1.jar source - INFO

### ISSUE THREAD

**Issue by cloudartist** [helli0n/kafka-monitoring#10]
hi Dmytro!

Great How-To. Just wanted to point out the source for JMXDiscovery-0.0.1.jar for any future readers.
https://github.com/RiotGamesMinions/zabbix_jmxdiscovery 

JMXDiscovery-0.0.1.jar seemed insecure for me, so I built it from source.

Feel free to close this issue anytime.

Thanks,
Marcin

**Comment by helli0n** [comment]
Updated README.md. Added link to the source of **jmxdiscovery**
