### ISSUE TITLE
kafka consumer monitoring template import failure

### ISSUE THREAD

**Issue by naveentech7** [helli0n/kafka-monitoring#17]
When i try to import zbx_templates_kafkaconsumers.xml template on zabbix server (4.0.7), got version not supported error.

So i have modified template version as 4.0 and when importing getting "the tag description missing error".

**Comment by helli0n** [comment]
I adde older zabbix template that you can use as new one doesn't support older zabbix versions

https://github.com/helli0n/kafka-monitoring/blob/master/kafkaconsumers/zbx_templates_kafkaconsumers3.0.xml

**Comment by naveentech7** [comment]
Thanks for your quick support, it worked :-)
