### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by aviramartac** [helli0n/kafka-monitoring#3]
Hi, thanks for your work.

For the steps under 'Kafka Configuration', I assume these are steps that I need to perform on all Kafka hosts? Not on the Zabbix Server host

Thanks

**Comment by helli0n** [comment]
Hello, 

Yes, that steps should be done on kafka servers (brokers) 

You're welcome

**Comment by aviramartac** [comment]
Okay,

And is there any reason you chose "12345" for Dcom.sun.management.jmxremote.port? or just random?
I know Zabbix Java Gateway uses port 10052

**Comment by helli0n** [comment]
Port **12345** doesn't relate to Zabbix Java Gateway. Port **12345** uses for JMX monitoring of **kafka broker**.

**Comment by aviramartac** [comment]
So let me see if I get this correctly:

Zabbix Server connects to Zabbix Java Gateway via port 10052.
Then Zabbix Java Gateway connects to the Kafka brokers via port 12345?

**Comment by helli0n** [comment]
Yes, 
You understood correct!

**Comment by aviramartac** [comment]
Okay and one final question:

Do I have to use port 12345 or can I just choose another available random port?

**Comment by helli0n** [comment]
You can use ports whatever you want
