### ISSUE TITLE
Use jmx.discovery instead of jmx_discovery

### ISSUE THREAD

**Issue by evgeniagusakova** [helli0n/kafka-monitoring#6]
Hi!

I faced with CPU usage by java process running 
```
java -jar JMXDiscovery-0.0.1.jar ...
```
on  my zabbix server.

For the first view for Zabbix 3.4 it is possible to use build-in jmx.discovery (dot VS underscore) instead if forking external java process with externalscripts 

Please take a look on Zabbix documentation:
https://www.zabbix.com/documentation/3.4/manual/discovery/low_level_discovery/jmx

Unfortunately it looks like syntax of build-in jmx**.**discovery differs from   jmx**_**discovery and I do not know Zabbix  (and Kafka) well so can't provide you pull request

Also, why do discovery interval is set for 30 seconds?
From my point of view it can be increase up to 10 mins or even more.

Thank you!

**Comment by helli0n** [comment]
You can change discovery interval in the template it is not big deal.
