### ISSUE TITLE
Value should be a JSON object.

### ISSUE THREAD

**Issue by ThomasBarach** [helli0n/kafka-monitoring#7]
Hello ! 

First of all, thanks a lot for you work!
My JMX icon turned green, however the discovery rules fail. The error is : Value should be a JSON object.

Is there a way to fix this ? 

Thanks
Thomas

**Comment by helli0n** [comment]
Hello, did you try to use scripts to check jmx metrics from the console? 

> #!/usr/bin/env bash
>
> ZBXGET="/usr/bin/zabbix_get"
> if [ $# != 5 ]
> then
> echo "Usage: $0 <JAVA_GATEWAY_HOST> <JAVA_GATEWAY_PORT> <JMX_SERVER> ><JMX_PORT> <KEY>"
> exit;
> fi
> QUERY="{\"request\": \"java gateway jmx\",\"conn\": \"$3\",\"port\": $4,\"keys\": [\"$5\"]}"
> $ZBXGET -s $1 -p $2 -k "$QUERY"

 eg.: ./zabb_get_java zabbix-java-gateway-ip 10052 server-test-ip 12345 'jmx[java.lang:type=Threading,PeakThreadCount]'

**Comment by ThomasBarach** [comment]
Yep, I tried it. 
But it looks like the JMX item protocol changed (I'm using Zabbix 3.4). I'm figuring out how to make your script works :)
I'll get back to you when this is done

**Comment by helli0n** [comment]
Which kafka version do you use? maybe kafka has changed some JMX metrics?

**Comment by ThomasBarach** [comment]
I'm using Kafka 1.0.0, the version released on November 1, 2017.

**Comment by helli0n** [comment]
Probably, the issue is in kafka side, not in Zabbix, because I use Zabbix 3.4 and it works as expected.

**Comment by 20100507** [comment]
@ThomasBarach I also used kafka1.0.0 and I have the same problem as you. I don't know how you solved it. Have you solved this problem?  Can you help me? Thanks!!
