### ISSUE TITLE
have some error

### ISSUE THREAD

**Issue by 20100507** [helli0n/kafka-monitoring#9]
My JMX icon turned green,but key Not supported, I use confluent-3.0.0. and I execute 
`./zabb_get_java 10.10.21.10 10052 10.10.21.10 5448 'jmx[java.lang:type=Threading,PeakThreadCount]'`
but have  a  error:
 ./zabb_get_java: line 9: gateway: command not found

Please tell me what should I do? 
Thank you very much !!

**Comment by helli0n** [comment]
Do you have **/usr/bin/zabbix_get** in your host?

**Comment by 20100507** [comment]
yes, I have /usr/bin/zabbix_get. I would like to ask if you do not set the -Dcom.sun.management.jmxremote.rmi.port=<REPLACE_WITH_YOUR_JMX_PORT> option, just set the -Dcom.sun.management.jmxremote.port=<REPLACE_WITH_YOUR_JMX_PORT> option, zabbix-server can be obtained normally Information~, there are a lot of keys that are not supported. The kafka I am using is version 0.10.0.0.

**Comment by helli0n** [comment]
You can check metrics using https://docs.oracle.com/javase/7/docs/technotes/guides/management/jconsole.html and than you should know metrics that kafka supports.

**Comment by 20100507** [comment]
I don't know which version of kafka you are using. I have used jconsole to observe it. There are some keys that really don't.
